# Define variables
IMAGE_NAME = your-image-name

# Build the Docker image
build:
  docker build -t $(IMAGE_NAME) .

# Run the Docker container
run:
  docker run $(IMAGE_NAME)

# Dev run
dev:
  dotnet watch run

